feat(matomo): add more device infos to tracking
ikuseiGmbH/smart-village-app-app pull request #276
Opened 2021-07-16 22:39 UTC by donni106

- created `userInfo` object from different sources and pass it to matomo tracking
  - ⚠️  matomo-tracker-react-native 0.3.0 is required for this to work!
    - PR: https://github.com/donni106/matomo-tracker-react-native/pull/6
  - `userInfo` contains app-version, language, screen resolution and an user agent to identify devices more detailed (still anonymously!)
  - added a new hook to build this object
- added new hook to async track screen view for a given `name` using the new user info hook

![Bildschirmfoto 2021-07-17 um 00 37 02](https://user-images.githubusercontent.com/1942953/126014826-e1c0f905-6687-4747-a60a-a9c76263f22a.png)

---

![Bildschirmfoto 2021-07-17 um 00 37 09](https://user-images.githubusercontent.com/1942953/126014827-705ef042-5a19-46e1-9351-9a8aadae755a.png) ![Bildschirmfoto 2021-07-17 um 00 37 14](https://user-images.githubusercontent.com/1942953/126014829-40034eed-9a08-46e5-b886-2c3f60d046bf.png) ![Bildschirmfoto 2021-07-17 um 00 37 18](https://user-images.githubusercontent.com/1942953/126014830-04dc4a2e-889c-4ccf-936e-7cb316d1d673.png) ![Bildschirmfoto 2021-07-17 um 00 37 22](https://user-images.githubusercontent.com/1942953/126014832-a7987c90-974b-4843-985a-105e4c679729.png) ![Bildschirmfoto 2021-07-17 um 00 37 26](https://user-images.githubusercontent.com/1942953/126014833-32910fbe-d5d2-4827-a4b1-43df2acf698a.png)

2021-07-23 12:40 UTC, digorath requested changes
Works great.

🛠️  Update the used package version before merging! 🛠️

2021-07-23 15:53 UTC, donni106 commented
TODO:

- [ ] update in src/screens/ConstructionSiteDetailScreen.js after #273 is merged

2021-07-29 17:01 UTC, donni106 commented
> Works great.
> 
> 🛠️ Update the used package version before merging! 🛠️

done. released 0.3.0 there and updated the dependency here.

2021-07-30 08:00 UTC, digorath approved these changes

2021-09-07 08:48 UTC, digorath commented
rebased onto new master -> only conflict was in package.json (differing version numbers of `expo-notifications`)

2021-09-07 08:48 UTC, merged