fix(lunch): wrong default for poiId
ikuseiGmbH/smart-village-app-app pull request #342
Opened 2021-09-28 16:21 UTC by digorath

## Changes proposed in this PR:

During the react navigation upgrade a wrong default was added to the `poiId` of the lunches, resulting in wrong filtering behaviour.

---

SVA-266

2021-09-28 17:01 UTC, donni106 requested changes

2021-09-28 17:01 UTC, donni106 commented on src/screens/LunchScreen.js
> +      <RegularText>{JSON.stringify(poiId)}</RegularText>
Is this logging and should be removed?

2021-09-28 17:17 UTC, digorath commented on src/screens/LunchScreen.js
> +      <RegularText>{JSON.stringify(poiId)}</RegularText>
Yes.

2021-09-29 17:13 UTC, donni106 approved these changes

2021-10-04 15:26 UTC, merged