feat(ar object): parse ar object
ikuseiGmbH/smart-village-app-app pull request #570
Opened 2022-07-08 13:42 UTC by ardasnturk

the files in local are all stored in an array
`viro` uses different types of data in different places
therefore we need to parse the array in local

- added parser to place all augmented
  reality objects where `viro` wants them

SVA-633

2022-07-13 14:47 UTC, donni106 requested changes

2022-07-14 08:22 UTC, ardasnturk commented on src/screens/augmentedReality/ARShowScreen.js
> +    }
Wow, that's a very good thought. I'm gonna try that. 👍

2022-07-15 12:38 UTC, ardasnturk commented on src/screens/augmentedReality/ARShowScreen.js
> +    await objectParser({ item: data[index], setObject });
https://github.com/ikuseiGmbH/smart-village-app-app/pull/570/commits/b8c10a78307e6211902d11a3b72befd8b34d9014

2022-07-15 13:02 UTC, donni106 approved these changes

2022-07-15 13:14 UTC, merged